
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - zhuangtongfa.material-theme
    - vscjava.vscode-java-test
    - vscjava.vscode-java-dependency
    - github.github-vscode-theme
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-maven
